export class CarModel{
  _id!: string; // The _id is a unique identifier generated by MongoDB
  Name!: string; // The name of the car
  Make!: string; // The make of the car
  Range!: number; // The range of the car
  Connector!: Connector; // The connector of the car
}

export class Connector{
  Type!: string; // The type of the connector
}
