export class EV_charger{
  _id!: string; // The _id is a unique identifier generated by MongoDB
  ChargeDeviceId!: string; // The id of the charger
  ChargeDeviceLatitude!: string; // The latitude of the charger
  ChargeDeviceLongitude!: string; // The longitude of the charger
  ChargeDeviceName?: string; // The name of the charger
  Connector?: Array<Connector>; // The connector of the charger
  PaymentRequiredFlag?: boolean; // The payment required flag of the charger
  ParkingFeesFlag?: boolean; // The parking fees flag of the charger
  Accessible24Hours?: boolean; // The accessible 24 hours flag of the charger
}

export class Connector{
  ConnectorType?: string; // The type of the connector
  RatedOutputkW?: string; // The rated output of the connector
  ChargePointStatus?: string; // The charge point status of the connector
}
