import { Time } from "@angular/common";

export class queue{
  id!: string; // The _id is a unique identifier generated by MongoDB
  empty: boolean; // The empty flag of the queue
  entity!: Array<place>; // The entity of the queue
}

export class place{
  car!: string; // The car in the queue
  time!: Time; // The time spent by this car in the queue
  place!: number; // The place of the car in the queue
  reserved!: boolean; // The reserved flag of the car in the queue
  localId?: Number; // The local id
  reserveEnd?: Date; // When the reservation ends
  timeEnd?: Date; // When the time ends
}
